image: docker:19.03.4-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""


stages:
  - build


Build Django App:
  stage: build
  tags:
    - docker
  services:
    - docker:19.03.4-dind
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t skyride/nginx-stream-kit-django:${CI_COMMIT_SHA} -t skyride/nginx-stream-kit-django:latest .
    - docker push skyride/nginx-stream-kit-django:${CI_COMMIT_SHA}

Build Nginx:
    stage: build
    tags:
        - docker
    services:
        - docker:19.03.4-dind
    script:
        - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
        - docker build -t skyride/nginx-stream-kit-nginx:${CI_COMMIT_SHA} -t skyride/nginx-stream-kit-nginx:latest nginx/
        - docker push skyride/nginx-stream-kit-nginx:${CI_COMMIT_SHA}

Build Nginx Ingest:
    stage: build
    tags:
        - docker
    services:
        - docker:19.03.4-dind
    script:
        - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
        - docker build -t skyride/nginx-stream-kit-ingest:${CI_COMMIT_SHA} -t skyride/nginx-stream-kit-ingest:latest nginx-rtmp/
        - docker push skyride/nginx-stream-kit-ingest:${CI_COMMIT_SHA}