stages:
  - build


Build Django App:
  stage: build
  tags:
    - docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/django:$CI_COMMIT_SHA
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

Build Nginx:
  stage: build
  tags:
    - docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_SHA
  script:
    - docker build --pull -t $IMAGE_TAG nginx/
    - docker push $IMAGE_TAG

Build RTMP Ingest:
  stage: build
  tags:
    - docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/ingest:$CI_COMMIT_SHA
  script:
    - docker build --pull -t $IMAGE_TAG nginx-rtmp/
    - docker push $IMAGE_TAG