version: "3.0"

services:
  nginx:
    image: skyride/nginx-stream-kit-nginx:${CI_COMMIT_SHA}

    volumes:
      - static:/static
      - media:/media
      - hls:/hls

  nginx-rtmp:
    image: skyride/nginx-stream-kit-ingest:${CI_COMMIT_SHA}
    volumes:
      - hls:/hls

  web:
    image: skyride/nginx-stream-kit-django:${CI_COMMIT_SHA}
    command: ./manage.py runserver 0:8000
    environment:
      - SECRET_KEY=586485tjdfgjtry5jhrtgh
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_REGION_NAME=${S3_REGION_NAME}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - nginx
      - nginx-rtmp

  postgres:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    volumes:
      - redisdata:/data
  
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  hls:
  pgdata:
  redisdata:
  rabbitmqdata:
  media:
  static: