version: "3.0"

services:
  nginx-rtmp:
    build:
      context: nginx-rtmp/
    ports:
      - 1935:1935
    volumes:
      - hls:/hls
    depends_on:
      - web

  web:
    build: .
    command: ./manage.py runserver 0:8000
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static:/static
      - media:/media
      - hls:/hls
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    volumes:
      - redisdata:/data

volumes:
  hls:
  pgdata:
  redisdata:
  media:
  static: