# Generated by Django 2.2.9 on 2020-01-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0019_auto_20200122_2145'),
        ('authorisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamkey',
            name='transcode_profiles',
            field=models.ManyToManyField(related_name='stream_keys', to='streams.TranscodeProfile'),
        ),
    ]
