# Generated by Django 2.2.9 on 2020-01-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0002_streamkey_transcode_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamkey',
            name='transcode_profiles',
            field=models.ManyToManyField(blank=True, related_name='stream_keys', to='streams.TranscodeProfile'),
        ),
    ]
