# Generated by Django 2.2.9 on 2020-01-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_auto_20200122_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamkey',
            name='default_stream_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
