# Generated by Django 2.2.9 on 2019-12-23 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stream_key', models.CharField(max_length=255)),
                ('app', models.CharField(default='', max_length=255)),
                ('flash_version', models.CharField(default='', max_length=255)),
                ('swf_url', models.CharField(default='', max_length=255)),
                ('tcurl', models.CharField(default='', max_length=255)),
                ('page_url', models.CharField(default='', max_length=255)),
                ('client_id', models.IntegerField(default=0)),
                ('source_ip', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
