# Generated by Django 2.2.9 on 2019-12-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_key',
            field=models.CharField(choices=[('live', 'Live'), ('finished', 'Finished')], max_length=32),
        ),
    ]
