# Generated by Django 2.2.9 on 2019-12-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20191223_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='started',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='stopped',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
