# Generated by Django 2.2.9 on 2019-12-23 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_auto_20191223_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='key',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
