# Generated by Django 2.2.9 on 2019-12-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_stream_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['created']},
        ),
    ]
