# Generated by Django 2.2.9 on 2020-01-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_distribution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distribution',
        ),
    ]
