# Generated by Django 2.2.9 on 2020-01-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0009_distribution_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscodeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('video_codec', models.CharField(max_length=64)),
                ('video_bitrate', models.IntegerField()),
                ('audio_codec', models.CharField(max_length=64)),
                ('audio_bitrate', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='transcode_profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='streams.TranscodeProfile'),
        ),
    ]
