# Generated by Django 2.2.9 on 2020-01-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_auto_20200118_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodeprofile',
            name='video_width',
            field=models.IntegerField(default=1280),
            preserve_default=False,
        ),
    ]
