# Generated by Django 2.2.9 on 2020-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0011_transcodeprofile_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodeprofile',
            name='video_preset',
            field=models.CharField(choices=[('ultrafast', 'Ultrafast'), ('superfast', 'Superfast'), ('veryfast', 'Veryfast'), ('faster', 'Faster'), ('fast', 'Fast'), ('medium', 'Medium'), ('slow', 'Slow'), ('slower', 'Slower'), ('veryslow', 'Veryslow'), ('placebo', 'Placebo')], default='veryfast', max_length=32),
        ),
    ]
