# Generated by Django 2.2.9 on 2020-01-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0012_transcodeprofile_video_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='transcode_command',
            field=models.TextField(blank=True),
        ),
    ]
