# Generated by Django 2.2.9 on 2020-01-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0013_segment_transcode_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='transcode_log',
            field=models.TextField(blank=True),
        ),
    ]
