# Generated by Django 2.2.9 on 2020-01-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0014_segment_transcode_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='transcode_log',
            new_name='transcode_stderr',
        ),
        migrations.AddField(
            model_name='segment',
            name='transcode_stdout',
            field=models.TextField(blank=True),
        ),
    ]
