# Generated by Django 2.2.9 on 2020-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0015_auto_20200118_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='transcode_stdout',
        ),
        migrations.AlterField(
            model_name='transcodeprofile',
            name='audio_codec',
            field=models.CharField(choices=[('libfdk_aac', 'AAC')], max_length=64),
        ),
        migrations.AlterField(
            model_name='transcodeprofile',
            name='video_codec',
            field=models.CharField(choices=[('libx264', 'h264'), ('libx265', 'h265 (HEVC)')], max_length=64),
        ),
    ]
