# Generated by Django 2.2.9 on 2020-01-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_auto_20200122_2146'),
        ('streams', '0019_auto_20200122_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams', to='authorisation.StreamKey'),
        ),
    ]
