# Generated by Django 2.2.9 on 2020-01-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0020_stream_stream_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='page_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stream',
            name='started',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stopped',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
