# Generated by Django 2.2.9 on 2020-01-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0021_auto_20200122_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
