# Generated by Django 2.2.9 on 2020-01-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0022_stream_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
