# Generated by Django 2.2.9 on 2020-02-01 14:54

import apps.streams.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0024_auto_20200125_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Still',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=apps.streams.models.generate_still_filename)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stills', to='streams.Segment')),
            ],
        ),
    ]
