# Generated by Django 2.2.9 on 2020-02-01 16:04

from django.db import migrations
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0025_still'),
    ]

    operations = [
        migrations.AddField(
            model_name='still',
            name='file_size',
            field=sizefield.models.FileSizeField(default=0),
            preserve_default=False,
        ),
    ]
